### ISSUE TITLE
connect your project to SonarQube

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team1#83]
_From @yossigil on November 14, 2018 9:40_

for now, just connect. later we shall decide which rules to use.

_Copied from original issue: TechnionYP5779/team5#128_

**Comment by ofiralexi** [comment]
there is an eclipse plug-in for sonarQube called sonarLint @dormaayan 
Should we download the plugin they made for eclipse or setup the sonarQube?
@dormaayan

**Comment by yossigil** [comment]
not the eclipse, the git hub

**Comment by ofiralexi** [comment]
@yossigil I don't think I fully understand your answer.
SonarQube is offered for Java in those cases:
-By adding it directly for Maven and Gradle projects
-By installing the eclipse plugin ( since we use eclipse)
**  There is a gitlab plugin of SonarQube but not one for github as mentioned both on their website and the github repository
** There is a github authentication plugin but I don't think that is what you meant since it is not reviewing the code like the regular sonarQube behaviour
So, which one of these options should we go with ?
Thank you in advance :).

**Comment by ShaiZeevi** [comment]
@ofiralexi I believe this might help: https://ballerina.io/learn/by-guide/sonarqube-github-integration/

**Comment by ShaiZeevi** [comment]
And I think this will be even more helpful
https://docs.travis-ci.com/user/sonarcloud/

**Comment by ofiralexi** [comment]
Integrated with our repo
![image](https://user-images.githubusercontent.com/37834992/48740030-8a873d80-ec5e-11e8-8189-464b79f8a5ea.png)
![image](https://user-images.githubusercontent.com/37834992/48740018-82c79900-ec5e-11e8-85c0-d2f852562a3f.png)

**Comment by yoavz1997** [comment]
Seems Legit! #79
